// <auto-generated />
namespace Ferma.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatemigrations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatemigrations));
        
        string IMigrationMetadata.Id
        {
            get { return "201903041719267_update-migrations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
