// <auto-generated />
namespace Ferma.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_class_Player : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_class_Player));
        
        string IMigrationMetadata.Id
        {
            get { return "201902271414300_Add_class_Player"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
